Merge tag 'v210' into bskyb/merge_v210
Also updated merged modules: gorouter, cloud controller and dea

diff --git a/jobs/etcd/templates/etcd_ctl.erb b/jobs/etcd/templates/etcd_ctl.erb
--- a/jobs/etcd/templates/etcd_ctl.erb
+++ b/jobs/etcd/templates/etcd_ctl.erb
@@ -1,57 +1,110 @@
 #!/bin/bash
 
+set -e -u -x
+
 RUN_DIR=/var/vcap/sys/run/etcd
-PIDFILE=$RUN_DIR/etcd.pid
-WORK_DIR=/var/vcap/store/etcd
-JOB_DIR=/var/vcap/jobs/etcd
+PIDFILE=${RUN_DIR}/etcd.pid
 
 source /var/vcap/packages/common/utils.sh
+
+source /var/vcap/jobs/etcd/bin/etcd_bosh_utils.sh
+
+wait_for_this_node_to_synchronize() {
+  for i in $(seq <%= p("etcd.log_sync_timeout_in_seconds") %>); do
+    if /var/vcap/packages/etcd/etcdctl -C ${advertise_client_url} ls; then
+      synced=true
+      break
+    fi
+    sleep 1
+  done
+}
+
 
 case $1 in
 
   start)
-    pid_guard $PIDFILE "etcd"
 
-	# horrible hack to get around etcd being not so good
-	rm -rf /var/vcap/store/etcd
+    pid_guard ${PIDFILE} "etcd"
 
-    mkdir -p $RUN_DIR
-    mkdir -p $WORK_DIR
+    if ! mountpoint -q ${STORE_DIR}; then
+      echo "$STORE_DIR must be a persistent disk"
+      exit 1
+    fi
 
-    chown -R vcap:vcap $RUN_DIR
-    chown -R vcap:vcap $WORK_DIR
+    mkdir -p ${RUN_DIR}
+    mkdir -p ${LOG_DIR}
+    mkdir -p ${DATA_DIR}
 
-    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
+    chown -R vcap:vcap ${RUN_DIR}
+    chown -R vcap:vcap ${LOG_DIR}
+    chown -R vcap:vcap ${DATA_DIR}
 
-    echo $$ > $PIDFILE
+    # Allowed number of open file descriptors
+    ulimit -n 100000
 
-    <% my_ip = spec.networks.send(properties.networks.apps).ip %>
-    <% my_host = spec.networks.send(properties.networks.apps).dns_record_name %>
+    prior_member_list=$(member_list)
 
-    exec chpst -u vcap:vcap /var/vcap/packages/etcd/etcd -snapshot -data-dir=$WORK_DIR \
-        -addr=<%= my_ip %>:4001 \
-        -peer-addr=<%= my_ip %>:7001 \
-        -name=<%= "#{name}-#{spec.index}-#{my_ip}" %> \
-        <%
-          # etcd crashes if all peers are missing. for the first deploy,
-          # we need at least one instance to come up without trying to
-          # connect to any peers.
-        %> \
-        <% if p("etcd.machines").length > 1 %> \
-          <% if p("etcd.machines").first != my_ip && p("etcd.machines").first != my_host %> \
-        -peers=<%= p("etcd.machines").reject { |ip| ip == my_ip || ip == my_host }.map { |m| "#{m}:7001" }.join(",") %> \
-          <% end %> \
-        <% end %> \
-        -peer-heartbeat-timeout=<%= p("heartbeat_interval_in_milliseconds") %>\
-        -peer-election-timeout=<%= p("election_timeout_in_milliseconds") %>
+    if [ -z "${prior_member_list}" ]; then
+      cluster_state=new
+      cluster="${this_node}"
+    else
+      cluster_state=existing
+      cluster=$(extract_cluster_from_member_list "${prior_member_list}")
+
+      # If this node is not in the existing cluster, add it. It generally should
+      # not be in the cluster, but if a prior shutdown failed to remove it, we
+      # don't want to have it duplicated in the list (etcd server will fail to
+      # start). Note extract_my_id determines membership solely based on IP, so
+      # this logic is not future-proof against changing node names or ports.
+      my_id=$(extract_my_id "${prior_member_list}")
+      if [ -z "${my_id}" ]; then
+        member_add
+        cluster="${cluster},${this_node}"
+      fi
+    fi
+
+    # Sleep to allow member_add to propagate to entire cluster because starting
+    # the server subsequently expects all peers to agree on the cluster members
+    sleep 2
+
+    chpst -u vcap:vcap /var/vcap/packages/etcd/etcd                                             \
+        --name                        ${node_name}                                              \
+        --data-dir                    ${DATA_DIR}                                               \
+        --heartbeat-interval          <%= p("etcd.heartbeat_interval_in_milliseconds") %> \
+        --election-timeout            <%= p("etcd.election_timeout_in_milliseconds") %>   \
+        --listen-peer-urls            ${listen_peer_url}                                        \
+        --listen-client-urls          ${listen_client_url}                                      \
+        --initial-advertise-peer-urls ${advertise_peer_url}                                     \
+        --advertise-client-urls       ${advertise_client_url}                                   \
+        --initial-cluster             ${cluster}                                                \
+        --initial-cluster-state       ${cluster_state}                                          \
+        2> >(tee -a ${LOG_DIR}/etcd.stderr.log | logger -t vcap.etcd)                           \
+        1> >(tee -a ${LOG_DIR}/etcd.stdout.log | logger -t vcap.etcd) &
+
+    etcd_pid=$!
+
+    synced=false
+    wait_for_this_node_to_synchronize # mutates $synced
+
+    if ${synced}; then
+      echo ${etcd_pid} > ${PIDFILE}
+      wait ${etcd_pid}
+    else
+      safe_teardown "${prior_member_list}"
+      kill -9 ${etcd_pid}
+      exit 1
+    fi
+
     ;;
 
   stop)
-    kill_and_wait $PIDFILE
+
+    kill_and_wait ${PIDFILE}
 
     ;;
 
   *)
+
     echo "Usage: etcd_ctl {start|stop}"
 
     ;;
