Merge v234

diff --git a/jobs/postgres/templates/postgres_ctl.erb b/jobs/postgres/templates/postgres_ctl.erb
--- a/jobs/postgres/templates/postgres_ctl.erb
+++ b/jobs/postgres/templates/postgres_ctl.erb
@@ -1,76 +1,107 @@
-#!/bin/bash -e
+#!/bin/bash -exu
 
-PACKAGE_DIR=/var/vcap/packages/postgres-9.4.2
-JOB_DIR=/var/vcap/jobs/postgres
-PACKAGE_DIR_OLD=/var/vcap/packages/postgres
+function main() {
+  local action
+  action="${1}"
 
-STORE_DIR=/var/vcap/store
-DATA_DIR=$STORE_DIR/postgres-9.4.2
-DATA_DIR_OLD=$STORE_DIR/postgres
+  local pgversion
+  pgversion="postgres-9.4.6"
 
-RUN_DIR=/var/vcap/sys/run/postgres
-LOG_DIR=/var/vcap/sys/log/postgres
+  JOB_DIR=/var/vcap/jobs/postgres
+  PACKAGE_DIR="/var/vcap/packages/${pgversion}"
+  STORE_DIR=/var/vcap/store
+  DATA_DIR="${STORE_DIR}/${pgversion}"
 
-# external_pid_file in postgresql.conf takes care of
-# overwriting $PIDFILE with actual DB server pid
-PIDFILE=$RUN_DIR/postgres.pid
+  PACKAGE_DIR_OLD=/var/vcap/packages/postgres-unknown
+  DATA_DIR_OLD="${STORE_DIR}/postgres-unknown"
 
-source /var/vcap/packages/common/utils.sh
+  if [[ -d "${STORE_DIR}/postgres-9.4.5" ]]; then
+    DATA_DIR_OLD="${STORE_DIR}/postgres-9.4.5"
+    PACKAGE_DIR_OLD=/var/vcap/packages/postgres-9.4.5
+  fi
 
-case "$1" in
-  start)
-    if [ -d $DATA_DIR_OLD -a -f $DATA_DIR_OLD/postgresql.conf ]; then
-      set +e
-      su - vcap -c "$PACKAGE_DIR/bin/pg_ctl stop -m fast -w -D $DATA_DIR"
-      su - vcap -c "$PACKAGE_DIR_OLD/bin/pg_ctl stop -m fast -w -D $DATA_DIR_OLD"
-      set -e
-    fi
+  if [[ -d "${STORE_DIR}/postgres-9.4.2" ]]; then
+    DATA_DIR_OLD="${STORE_DIR}/postgres-9.4.2"
+    PACKAGE_DIR_OLD=/var/vcap/packages/postgres-9.4.2
+  fi
 
-    pid_guard $PIDFILE "PostgreSQL"
+  RUN_DIR=/var/vcap/sys/run/postgres
+  LOG_DIR=/var/vcap/sys/log/postgres
 
-    # TODO: This script is responsible for both
-    # starting PostgreSQL and running some queries
-    # (create DBs, roles, applying grants). One problem
-    # that needs to be addressed in the future is that
-    # if some queries fail job is still considered running.
-    # Later we'll change it to use a more involved approach
-    # (i.e. script that brings DB to sync)
+  # external_pid_file in postgresql.conf takes care of
+  # overwriting $PIDFILE with actual DB server pid
+  PIDFILE="${RUN_DIR}/postgres.pid"
 
-    mkdir -p $RUN_DIR
-    chown vcap:vcap $RUN_DIR
+  set +u
+  source /var/vcap/packages/common/utils.sh
+  set -u
 
-    echo "" > $PIDFILE
-    chown vcap:vcap $PIDFILE
+  case "${action}" in
+    "start")
+      if [ -d "${DATA_DIR_OLD}" -a -f "${DATA_DIR_OLD}/postgresql.conf" ]; then
+        set +e
+        su - vcap -c "${PACKAGE_DIR}/bin/pg_ctl stop -m fast -w -D ${DATA_DIR}"
+        su - vcap -c "${PACKAGE_DIR_OLD}/bin/pg_ctl stop -m fast -w -D ${DATA_DIR_OLD}"
+        set -e
+      fi
 
-    if [ ! -d $LOG_DIR ]; then
-      mkdir -p $LOG_DIR
-      chown vcap:vcap $LOG_DIR
-    fi
+      pid_guard "${PIDFILE}" "PostgreSQL"
 
-    # nimbus2 postgres backup - start
-    chmod +x $JOB_DIR/bin/postgres_backup
-    $JOB_DIR/bin/postgres_backup start
-    # nimbus2 postgres backup - end
+      # TODO: This script is responsible for both
+      # starting PostgreSQL and running some queries
+      # (create DBs, roles, applying grants). One problem
+      # that needs to be addressed in the future is that
+      # if some queries fail job is still considered running.
+      # Later we'll change it to use a more involved approach
+      # (i.e. script that brings DB to sync)
 
-    exec $JOB_DIR/bin/postgres_start.sh
-    ;;
+      mkdir -p "${RUN_DIR}"
+      chown vcap:vcap "${RUN_DIR}"
 
-  stop)
-    echo "Stopping PostgreSQL: "
-    su - vcap -c "$PACKAGE_DIR/bin/pg_ctl stop -m fast -w -D $DATA_DIR"
-    wait_pidfile $PIDFILE
+      echo "" > "${PIDFILE}"
+      chown vcap:vcap "${PIDFILE}"
 
-    ;;
+      if [ ! -d "${LOG_DIR}" ]; then
+        mkdir -p "${LOG_DIR}"
+        chown vcap:vcap "${LOG_DIR}"
+      fi
 
-  status)
-    su - vcap -c "$PACKAGE_DIR/bin/pg_ctl status -D $DATA_DIR"
+      # nimbus2 postgres backup - start
+      chmod +x $JOB_DIR/bin/postgres_backup
+      $JOB_DIR/bin/postgres_backup start
+      # nimbus2 postgres backup - end
 
-    ;;
+      exec "${JOB_DIR}/bin/postgres_start.sh"
+      ;;
 
-  *)
-    echo "Usage: $0 {start|stop|status}"
-    exit 1
+    "stop")
+      echo "Stopping PostgreSQL: "
+      if [ -d "${DATA_DIR_OLD}" -a -f "${DATA_DIR_OLD}/postgresql.conf" ]; then
+        set +e
+        su - vcap -c "${PACKAGE_DIR_OLD}/bin/pg_ctl stop -m fast -w -D ${DATA_DIR_OLD}"
+        set -e
+      fi
 
-    ;;
+      su - vcap -c "${PACKAGE_DIR}/bin/pg_ctl stop -m fast -w -D ${DATA_DIR}"
 
-esac
+      set +u
+      wait_pidfile "${PIDFILE}"
+      set -u
+
+      ;;
+
+    "status")
+      su - vcap -c "${PACKAGE_DIR}/bin/pg_ctl status -D ${DATA_DIR}"
+
+      ;;
+
+    *)
+      echo "Usage: ${0} {start|stop|status}"
+      exit 1
+
+      ;;
+
+  esac
+}
+
+main "${1}"
diff --git a/jobs/postgres/templates/postgres_start.sh.erb b/jobs/postgres/templates/postgres_start.sh.erb
--- a/jobs/postgres/templates/postgres_start.sh.erb
+++ b/jobs/postgres/templates/postgres_start.sh.erb
@@ -1,132 +1,142 @@
-#!/bin/bash -e
+#!/bin/bash -exu
 
-JOB_DIR=/var/vcap/jobs/postgres
-PACKAGE_DIR=/var/vcap/packages/postgres-9.4.2
-PACKAGE_DIR_OLD=/var/vcap/packages/postgres
+function main() {
+  local pgversion
+  pgversion="postgres-9.4.6"
 
-STORE_DIR=/var/vcap/store
-DATA_DIR=$STORE_DIR/postgres-9.4.2
-DATA_DIR_OLD=$STORE_DIR/postgres
-DATA_DIR_PREVIOUS=$STORE_DIR/postgres-previous
+  JOB_DIR=/var/vcap/jobs/postgres
+  PACKAGE_DIR="/var/vcap/packages/${pgversion}"
+  STORE_DIR=/var/vcap/store
+  DATA_DIR="${STORE_DIR}/${pgversion}"
 
-RUN_DIR=/var/vcap/sys/run/postgres
-PIDFILE=$RUN_DIR/postgres.pid
+  DATA_DIR_PREVIOUS="${STORE_DIR}/postgres-previous"
+  DATA_DIR_OLD="${STORE_DIR}/postgres-unknown"
 
-HOST='0.0.0.0'
-PORT="<%= p("databases.port") %>"
-LD_LIBRARY_PATH=$PACKAGE_DIR/lib:$LD_LIBRARY_PATH
-
-if [ -d $DATA_DIR -a -f $STORE_DIR/FLAG_POSTGRES_UPGRADE ]; then
-  echo "FAIL: DB upgrade stopped in the middle, manual intervention required, quitting..."
-  exit 1
-fi
-
-sysctl -w "kernel.shmmax=284934144"
-
-if [ ! -d $STORE_DIR ]; then
-  echo "ERROR: storage directory doesn't exist"
-  echo "Please add persistent disk to this job"
-  exit 1
-fi
-
-if [ ! -d $DATA_DIR -o ! -f $DATA_DIR/postgresql.conf ]; then
-  mkdir -p $DATA_DIR
-  chown vcap:vcap $DATA_DIR
-
-  # initdb creates data directories
-  su - vcap -c "$PACKAGE_DIR/bin/initdb -E utf8 --locale en_US.UTF-8 -D $DATA_DIR"
-
-  mkdir -p $DATA_DIR/pg_log
-  chown vcap:vcap $DATA_DIR/pg_log
-fi
-
-if [ -d $DATA_DIR_OLD -a -f $DATA_DIR_OLD/postgresql.conf ]; then
-
-  if [ -d $DATA_DIR_PREVIOUS ]; then
-    rm -rf $DATA_DIR_PREVIOUS
+  if [[ -d "${STORE_DIR}/postgres-9.4.5" ]]; then
+    DATA_DIR_OLD="${STORE_DIR}/postgres-9.4.5"
   fi
 
-  touch $STORE_DIR/FLAG_POSTGRES_UPGRADE
+  if [[ -d "${STORE_DIR}/postgres-9.4.2" ]]; then
+    DATA_DIR_OLD="${STORE_DIR}/postgres-9.4.2"
+  fi
 
-  # Prevent upgrade from overwriting PIDFILE with new process during upgrade
-  chown root:root $PIDFILE
+  RUN_DIR=/var/vcap/sys/run/postgres
+  PIDFILE="${RUN_DIR}/postgres.pid"
 
-  su - vcap -c "$PACKAGE_DIR/bin/pg_upgrade \
-    --old-datadir $DATA_DIR_OLD \
-    --new-datadir $DATA_DIR \
-    --old-bindir $PACKAGE_DIR_OLD/bin \
-    --new-bindir $PACKAGE_DIR/bin"
+  HOST="0.0.0.0"
+  PORT="<%= p("databases.port") %>"
 
-  chown vcap:vcap $PIDFILE
+  if [[ -n "${LD_LIBRARY_PATH:-}" ]]; then
+    LD_LIBRARY_PATH="${PACKAGE_DIR}/lib:${LD_LIBRARY_PATH}"
+  else
+    LD_LIBRARY_PATH="${PACKAGE_DIR}/lib"
+  fi
 
-  rm -f $STORE_DIR/FLAG_POSTGRES_UPGRADE
-  mv $DATA_DIR_OLD $DATA_DIR_PREVIOUS
-fi
+  sysctl -w "kernel.shmmax=284934144"
 
-cp $JOB_DIR/config/{postgresql,pg_hba}.conf $DATA_DIR
-chown vcap:vcap $DATA_DIR/{postgresql,pg_hba}.conf
+  if [ ! -d "${STORE_DIR}" ]; then
+    echo "ERROR: storage directory doesn't exist"
+    echo "Please add persistent disk to this job"
+    exit 1
+  fi
 
-echo "Starting PostgreSQL: "
-su - vcap -c "$PACKAGE_DIR/bin/pg_ctl -o \"-h $HOST -p $PORT\" \
-              -w start -D $DATA_DIR -l \"$DATA_DIR/pg_log/startup.log\""
+  if [ -d "${DATA_DIR_OLD}" -a -f "${DATA_DIR_OLD}/postgresql.conf" ]; then
+    rm -rf "${DATA_DIR_PREVIOUS}"
 
-echo "PostgreSQL started successfully"
+    cp -r "${DATA_DIR_OLD}" "${DATA_DIR}"
+    mv "${DATA_DIR_OLD}" "${DATA_DIR_PREVIOUS}"
+  fi
 
-echo "Creating roles..."
-<% p("databases.roles", []).each do |role| %>
-  echo "Trying to create role <%= role["name"] %>..."
-  set +e
-  # TODO remove unused roles automatically
-  # Default permissions are: nosuperuser nologin inherit nocreatedb.
-  # Will fail if role already exists, which is OK
-  $PACKAGE_DIR/bin/psql -U vcap -p $PORT -d postgres \
-                        -c "CREATE ROLE \"<%= role["name"] %>\""
-  set -e
+  mkdir -p "${DATA_DIR}"
+  chown -R vcap:vcap "${DATA_DIR}"
 
-  echo "Setting password for role <%= role["name"] %>..."
-  $PACKAGE_DIR/bin/psql -U vcap -p $PORT -d postgres \
-                        -c "ALTER ROLE \"<%= role["name"] %>\" \
-                            WITH LOGIN PASSWORD '<%= role["password"] %>'"
+  if [ ! -f "${DATA_DIR}/postgresql.conf" ]; then
+    # initdb creates data directories
+    su - vcap -c "${PACKAGE_DIR}/bin/initdb -E utf8 --locale en_US.UTF-8 -D ${DATA_DIR}"
 
-  <% if role["permissions"] %>
-    echo "Adding permissions <%= role["permissions"].join(' ') %> for role <%= role["name"] %>..."
-    $PACKAGE_DIR/bin/psql -U vcap -p $PORT -d postgres \
-                      -c "ALTER ROLE \"<%= role["name"] %>\" \
-                          WITH <%= role["permissions"].join(' ') %>"
-  <% end %>
-<% end %>
+    mkdir -p "${DATA_DIR}/pg_log"
+    chown vcap:vcap "${DATA_DIR}/pg_log"
+  fi
 
-echo "Creating databases..."
-<% p("databases.databases", []).each do |database| %>
-  echo "Trying to create database <%= database["name"] %>..."
-  set +e
-  su - vcap -c "$PACKAGE_DIR/bin/createdb \"<%= database["name"] %>\" -p $PORT"
-  set -e
+  cp "${JOB_DIR}/config/postgresql.conf" "${JOB_DIR}/config/pg_hba.conf" "${DATA_DIR}"
+  chown vcap:vcap "${DATA_DIR}/postgresql.conf" "${DATA_DIR}/pg_hba.conf"
 
-  <% if database["citext"] %>
-    echo "Trying to install citext..."
+  echo "Starting PostgreSQL: "
+  su - vcap -c "${PACKAGE_DIR}/bin/pg_ctl -o \"-h ${HOST} -p ${PORT}\" \
+                  -w start -D ${DATA_DIR} -l \"${DATA_DIR}/pg_log/startup.log\""
+
+  echo "PostgreSQL started successfully"
+
+  create_roles
+  create_databases
+}
+
+function pgexec() {
+  local database
+  database="${1}"
+
+  local command
+  command="${2}"
+
+  "${PACKAGE_DIR}/bin/psql" \
+    -U "vcap" \
+    -p "${PORT}" \
+    -d "${database}" \
+    -c "${command}"
+}
+
+function create_roles() {
+  echo "Creating roles..."
+  <% p("databases.roles", []).each do |role| %>
+    echo "Trying to create role <%= role["name"] %>..."
     set +e
-    $PACKAGE_DIR/bin/psql -U vcap -p $PORT \
-                          -d "<%= database["name"] %>" \
-                          -c "CREATE EXTENSION citext"
-    $PACKAGE_DIR/bin/psql -U vcap -p $PORT \
-                          -d "<%= database["name"] %>" \
-                          -c "CREATE EXTENSION citext FROM UNPACKAGED"
+    # TODO remove unused roles automatically
+    # Default permissions are: nosuperuser nologin inherit nocreatedb.
+    # Will fail if role already exists, which is OK
+    pgexec postgres "CREATE ROLE \"<%= role["name"] %>\""
     set -e
-  <% end %>
 
-  <% if p("databases.collect_statement_statistics") %>
-    echo "Enabling pg_stat_statements extension..."
-    $PACKAGE_DIR/bin/psql -U vcap -p $PORT \
-                          -d "<%= database["name"] %>" \
-                          -c "CREATE EXTENSION IF NOT EXISTS pg_stat_statements"
-  <% end %>
+    echo "Setting password for role <%= role["name"] %>..."
+    pgexec postgres "ALTER ROLE \"<%= role["name"] %>\" WITH LOGIN PASSWORD '<%= role["password"] %>'"
 
-  <% if database["run_on_every_startup"] %>
-    <% database["run_on_every_startup"].each do |query| %>
-      $PACKAGE_DIR/bin/psql -U vcap -p $PORT \
-                            -d "<%= database["name"] %>" \
-                            -c "<%= query %>"
+    <% if role["permissions"] %>
+      echo "Adding permissions <%= role["permissions"].join(' ') %> for role <%= role["name"] %>..."
+      pgexec postgres "ALTER ROLE \"<%= role["name"] %>\" WITH <%= role["permissions"].join(' ') %>"
     <% end %>
   <% end %>
-<% end %>
+}
+
+function create_databases() {
+  echo "Creating databases..."
+  <% p("databases.databases", []).each do |database| %>
+    echo "Trying to create database <%= database["name"] %>..."
+    set +e
+    su - vcap -c "${PACKAGE_DIR}/bin/createdb \"<%= database["name"] %>\" -p ${PORT}"
+    set -e
+
+    <% if database["citext"] %>
+      echo "Trying to install citext..."
+      set +e
+      pgexec "<%= database["name"] %>" "CREATE EXTENSION citext"
+      pgexec "<%= database["name"] %>" "CREATE EXTENSION citext FROM UNPACKAGED"
+      set -e
+    <% end %>
+
+    echo "Enabling pgcrypto extension..."
+    pgexec "<%= database["name"] %>" "CREATE EXTENSION IF NOT EXISTS pgcrypto"
+
+
+    <% if p("databases.collect_statement_statistics") %>
+      echo "Enabling pg_stat_statements extension..."
+      pgexec "<%= database["name"] %>" "CREATE EXTENSION IF NOT EXISTS pg_stat_statements"
+    <% end %>
+
+    <% if database["run_on_every_startup"] %>
+      <% database["run_on_every_startup"].each do |query| %>
+        pgexec "<%= database["name"] %>" "<%= query %>"
+      <% end %>
+    <% end %>
+  <% end %>
+}
+
+main
diff --git a/packages/route_registrar/packaging b/packages/route_registrar/packaging
--- a/packages/route_registrar/packaging
+++ b/packages/route_registrar/packaging
@@ -1,6 +1,16 @@
-set -e -x
+#!/usr/bin/env bash
 
-cp -a * ${BOSH_INSTALL_TARGET}
-cd ${BOSH_INSTALL_TARGET}/route_registrar
+set -eux
 
-/var/vcap/packages/ruby-2.1.7/bin/bundle install --local --deployment
+mkdir -p ${BOSH_INSTALL_TARGET}/src
+cp -a . ${BOSH_INSTALL_TARGET}/src
+
+export GOPATH=$BOSH_INSTALL_TARGET
+
+export GOROOT=$(readlink -nf /var/vcap/packages/golang1.5)
+export PATH=$GOROOT/bin:$PATH
+
+go install github.com/cloudfoundry-incubator/route-registrar
+
+# clean up source artifacts
+rm -rf ${BOSH_INSTALL_TARGET}/src ${BOSH_INSTALL_TARGET}/pkg
